package com.Mod.api.util.map;

import com.google.common.collect.ImmutableMap;
import com.seedfinding.mcbiome.biome.Biome;
import com.seedfinding.mccore.block.Blocks;
import com.seedfinding.mccore.state.Dimension;
import com.seedfinding.mccore.version.MCVersion;
import net.minecraft.block.Block;

import java.util.Map;

import static com.seedfinding.mcbiome.biome.Biomes.*;
import static net.minecraft.init.Blocks.*;

import java.util.Map;

public class SimpleBlockMap {
    private static final Map<MCVersion, Map<Biome, Map<Block, Integer>>> versionedBiomeMap = ImmutableMap.<MCVersion, Map<Biome, Map<Block, Integer>>>builder()
            .put(MCVersion.v1_12_2, ImmutableMap.<Biome, Map<Block, Integer>>builder()
                    .put(OCEAN, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(GRAVEL, 1)
                            .put(SAND, 1)
                            .put(DIRT, 1)
                            .put(CLAY, 1)
                            .build()
                    ).put(PLAINS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(TALLGRASS, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(YELLOW_FLOWER, 0)
                            .put(RED_FLOWER, 0)

                            .put(GRASS, 0)
                            .build()
                    ).put(DESERT, ImmutableMap.<Block, Integer>builder()
                            .put(SAND, 1)
                            .put(SANDSTONE, 1)
                            .put(CACTUS, 0)
                            .put(DEADBUSH, 0)
                            .build()
                    ).put(MOUNTAINS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(STONE, 1)
                            .put(MONSTER_EGG, 1)
                            .put(EMERALD_ORE, 1)
                            .put(COAL_ORE, 1)
                            .put(IRON_ORE, 1)
                            .put(SNOW, 0)
                            .put(ICE, 1)

                            .put(GRASS, 0)
                            .put(RED_FLOWER, 0)
                            .put(YELLOW_FLOWER, 0)
                            .build()
                    ).put(FOREST, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(DOUBLE_PLANT, 0)

                            .put(GRASS, 0)
                            .build()
                    ).put(TAIGA, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(GRASS, 0)
                            .put(TALLGRASS, 0)
                            .put(DOUBLE_PLANT, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .build()
                    ).put(SWAMP, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(WATER, 9)
                            .put(WATERLILY, 0)
                            .put(CLAY, 1)
                            .put(VINE, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(RED_FLOWER, 0)
                            .put(RED_MUSHROOM, 0)
                            .put(BROWN_MUSHROOM, 0)
                            .put(DEADBUSH, 0)

                            .put(GRASS, 0)
                            .build()
                    ).put(RIVER, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(DIRT, 1)
                            .put(CLAY, 1)
                            .put(SAND, 1)
                            .put(GRAVEL, 1)
                            .put(REEDS, 0)
                            .build()
                    ).put(THE_END, ImmutableMap.<Block, Integer>builder()
                            .put(END_STONE, 121)
                            .put(OBSIDIAN, 0)
                            .put(BEDROCK, 0)
                            .build()
                    ).put(FROZEN_OCEAN, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(ICE, 1)
                            .put(SNOW, 1)
                            .put(PACKED_ICE, 1)
                            .put(GRAVEL, 1)
                            .put(SAND, 1)
                            .put(CLAY, 1)
                            .put(DIRT, 1)
                            .build()
                    ).put(FROZEN_RIVER, ImmutableMap.<Block, Integer>builder()
                            .put(ICE, 1)
                            .put(WATER, 9)
                            .put(DIRT, 1)
                            .put(CLAY, 1)
                            .put(SAND, 1)
                            .put(GRAVEL, 1)
                            .build()
                    ).put(SNOWY_TUNDRA, ImmutableMap.<Block, Integer>builder()
                            .put(SNOW, 0)
                            .put(DIRT, 1)
                            .put(ICE, 1)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .build()
                    ).put(SNOWY_MOUNTAINS, ImmutableMap.<Block, Integer>builder()
                            .put(SNOW, 0)
                            .put(DIRT, 1)
                            .put(ICE, 1)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .build()
                    ).put(MUSHROOM_FIELDS, ImmutableMap.<Block, Integer>builder()
                            .put(MYCELIUM, 1)
                            .put(RED_MUSHROOM_BLOCK, 0)
                            .put(BROWN_MUSHROOM_BLOCK, 0)
                            .put(RED_MUSHROOM, 0)
                            .put(BROWN_MUSHROOM, 0)
                            .build()
                    ).put(MUSHROOM_FIELD_SHORE, ImmutableMap.<Block, Integer>builder()
                            .put(MYCELIUM, 1)
                            .put(RED_MUSHROOM_BLOCK, 0)
                            .put(BROWN_MUSHROOM_BLOCK, 0)
                            .put(RED_MUSHROOM, 0)
                            .put(BROWN_MUSHROOM, 0)
                            .build()
                    ).put(BEACH, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(SAND, 1)
                            .put(SANDSTONE, 1)
                            .put(GRAVEL, 1)
                            .put(DIRT, 1)
                            .put(CLAY, 1)
                            .put(REEDS, 0)
                            .build()
                    ).put(DESERT_HILLS, ImmutableMap.<Block, Integer>builder()
                            .put(SAND, 1)
                            .put(SANDSTONE, 1)
                            .put(CACTUS, 0)
                            .put(DEADBUSH, 0)
                            .build()
                    ).put(WOODED_HILLS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(DOUBLE_PLANT, 0)

                            .put(GRASS, 0)
                            .build()
                    ).put(TAIGA_HILLS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(GRASS, 0)
                            .put(TALLGRASS, 0)
                            .put(DOUBLE_PLANT, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .build()
                    ).put(MOUNTAIN_EDGE, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(STONE, 1)
                            .put(MONSTER_EGG, 1)
                            .put(EMERALD_ORE, 1)
                            .put(COAL_ORE, 1)
                            .put(IRON_ORE, 1)
                            .put(SNOW, 0)
                            .put(ICE, 1)
                            .build()
                    ).put(JUNGLE, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(VINE, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(COCOA, 0)
                            .put(MELON_BLOCK, 0)
                            .build()
                    ).put(JUNGLE_HILLS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(VINE, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(COCOA, 0)
                            .put(MELON_BLOCK, 0)
                            .build()
                    ).put(JUNGLE_EDGE, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(VINE, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(COCOA, 0)
                            .put(MELON_BLOCK, 0)
                            .build()
                    ).put(DEEP_OCEAN, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(GRAVEL, 1)
                            .put(MAGMA, 1)
                            .put(OBSIDIAN, 1)
                            .build()
                    ).put(STONE_SHORE, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(STONE, 1)
                            .put(GRAVEL, 1)
                            .build()
                    ).put(SNOWY_BEACH, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(SNOW, 0)
                            .put(ICE, 1)
                            .put(SAND, 1)
                            .put(SANDSTONE, 1)
                            .put(GRAVEL, 1)
                            .put(DIRT, 1)
                            .put(CLAY, 1)
                            .build()
                    ).put(BIRCH_FOREST, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(DOUBLE_PLANT, 0)

                            .put(GRASS, 0)
                            .put(RED_FLOWER, 0)
                            .build()
                    ).put(BIRCH_FOREST_HILLS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(DOUBLE_PLANT, 0)

                            .put(GRASS, 0)
                            .put(YELLOW_FLOWER, 0)
                            .build()
                    ).put(DARK_FOREST, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(RED_MUSHROOM_BLOCK, 0)
                            .put(BROWN_MUSHROOM_BLOCK, 0)
                            .put(DOUBLE_PLANT, 0)

                            .put(GRASS, 0)
                            .put(RED_FLOWER, 0)
                            .build()
                    ).put(SNOWY_TAIGA, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(SNOW, 0)
                            .put(GRASS, 0)
                            .put(TALLGRASS, 0)
                            .put(DOUBLE_PLANT, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .build()
                    ).put(SNOWY_TAIGA_HILLS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(SNOW, 0)
                            .put(GRASS, 0)
                            .put(TALLGRASS, 0)
                            .put(DOUBLE_PLANT, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .build()
                    ).put(GIANT_TREE_TAIGA, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(MOSSY_COBBLESTONE, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(TALLGRASS, 0)
                            .put(DOUBLE_PLANT, 0)
                            .put(DEADBUSH, 0)
                            .put(RED_MUSHROOM, 0)
                            .put(BROWN_MUSHROOM, 0)
                            .build()
                    ).put(GIANT_TREE_TAIGA_HILLS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(MOSSY_COBBLESTONE, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(TALLGRASS, 0)
                            .put(DOUBLE_PLANT, 0)
                            .put(DEADBUSH, 0)
                            .put(RED_MUSHROOM, 0)
                            .put(BROWN_MUSHROOM, 0)
                            .build()
                    ).put(WOODED_MOUNTAINS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(STONE, 1)
                            .put(MONSTER_EGG, 1)
                            .put(EMERALD_ORE, 1)
                            .put(COAL_ORE, 1)
                            .put(IRON_ORE, 1)
                            .put(SNOW, 0)
                            .put(ICE, 1)

                            .put(GRASS, 0)
                            .put(RED_FLOWER, 0)
                            .build()
                    ).put(SAVANNA, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(GRASS, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)

                            .put(RED_FLOWER, 0)
                            .build()
                    ).put(SAVANNA_PLATEAU, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(TALLGRASS, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)

                            .put(GRASS, 0)
                            .build()
                    ).put(BADLANDS, ImmutableMap.<Block, Integer>builder()
                            .put(SAND, 1)
                            .put(HARDENED_CLAY, 1)
                            .put(STAINED_HARDENED_CLAY, 1)
                            .put(CACTUS, 0)
                            .put(DEADBUSH, 0)
                            .put(GOLD_ORE, 1)
                            .build()
                    ).put(WOODED_BADLANDS_PLATEAU, ImmutableMap.<Block, Integer>builder()
                            .put(SAND, 1)
                            .put(HARDENED_CLAY, 1)
                            .put(STAINED_HARDENED_CLAY, 1)
                            .put(CACTUS, 0)
                            .put(DEADBUSH, 0)
                            .put(GOLD_ORE, 1)
                            .put(DIRT, 1)
                            .put(LOG, 1)
                            .put(LEAVES, 1)
                            .build()
                    ).put(BADLANDS_PLATEAU, ImmutableMap.<Block, Integer>builder()
                            .put(SAND, 1)
                            .put(HARDENED_CLAY, 1)
                            .put(STAINED_HARDENED_CLAY, 1)
                            .put(CACTUS, 0)
                            .put(DEADBUSH, 0)
                            .put(GOLD_ORE, 1)
                            .build()
                    ).put(SMALL_END_ISLANDS, ImmutableMap.<Block, Integer>builder()
                            .put(END_STONE, 121)
                            .build()
                    ).put(END_MIDLANDS, ImmutableMap.<Block, Integer>builder()
                            .put(END_STONE, 121)
                            .build()
                    ).put(END_HIGHLANDS, ImmutableMap.<Block, Integer>builder()
                            .put(END_STONE, 121)
                            .put(CHORUS_PLANT, 0)
                            .put(CHORUS_FLOWER, 0)
                            .build()
                    ).put(END_BARRENS, ImmutableMap.<Block, Integer>builder()
                            .put(END_STONE, 121)
                            .build()
                    ).put(WARM_OCEAN, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(GRAVEL, 1)
                            .put(SAND, 1)
                            .put(DIRT, 1)
                            .put(CLAY, 1)
                            .put(MAGMA, 1)
                            .put(OBSIDIAN, 1)
                            .build()
                    ).put(LUKEWARM_OCEAN, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(GRAVEL, 1)
                            .put(SAND, 1)
                            .put(DIRT, 1)
                            .put(CLAY, 1)
                            .build()
                    ).put(COLD_OCEAN, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(GRAVEL, 1)
                            .put(SAND, 1)
                            .put(DIRT, 1)
                            .put(CLAY, 1)
                            .build()
                    ).put(DEEP_WARM_OCEAN, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(SAND, 1)
                            .put(MAGMA, 1)
                            .put(OBSIDIAN, 1)
                            .build()
                    ).put(DEEP_LUKEWARM_OCEAN, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(SAND, 1)
                            .put(MAGMA, 1)
                            .put(OBSIDIAN, 1)
                            .build()
                    ).put(DEEP_COLD_OCEAN, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(GRAVEL, 1)
                            .put(MAGMA, 1)
                            .put(OBSIDIAN, 1)
                            .build()
                    ).put(DEEP_FROZEN_OCEAN, ImmutableMap.<Block, Integer>builder()
                            .put(WATER, 9)
                            .put(SNOW, 1)
                            .put(SNOW_LAYER, 1)
                            .put(PACKED_ICE, 1)
                            .put(ICE, 1)
                            .put(GRAVEL, 1)
                            .put(MAGMA, 1)
                            .put(OBSIDIAN, 1)
                            .build()
                    ).put(THE_VOID, ImmutableMap.<Block, Integer>builder()
                            .put(COBBLESTONE, 1)
                            .put(STONE, 1)
                            .build()
                    ).put(SUNFLOWER_PLAINS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(TALLGRASS, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(RED_FLOWER, 0)
                            .put(DOUBLE_PLANT, 0)
                            .build()
                    ).put(DESERT_LAKES, ImmutableMap.<Block, Integer>builder()
                            .put(SAND, 1)
                            .put(SANDSTONE, 1)
                            .put(CACTUS, 0)
                            .put(DEADBUSH, 0)
                            .put(WATER, 9)
                            .put(REEDS, 0)
                            .build()
                    ).put(GRAVELLY_MOUNTAINS, ImmutableMap.<Block, Integer>builder()
                            .put(GRAVEL, 1)
                            .put(DIRT, 1)
                            .put(SNOW, 0)
                            .put(STONE, 1)
                            .put(MONSTER_EGG, 1)
                            .put(EMERALD_ORE, 1)
                            .put(COAL_ORE, 1)
                            .put(IRON_ORE, 1)
                            .build()
                    ).put(FLOWER_FOREST, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(DOUBLE_PLANT, 0)
                            .put(RED_FLOWER, 0)
                            .build()
                    ).put(TAIGA_MOUNTAINS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(GRASS, 0)
                            .put(TALLGRASS, 0)
                            .put(DOUBLE_PLANT, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .build()
                    ).put(SWAMP_HILLS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(WATER, 9)
                            .put(WATERLILY, 0)
                            .put(CLAY, 1)
                            .put(VINE, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(RED_FLOWER, 0)
                            .put(RED_MUSHROOM, 0)
                            .put(BROWN_MUSHROOM, 0)
                            .build()
                    ).put(ICE_SPIKES, ImmutableMap.<Block, Integer>builder()
                            .put(PACKED_ICE, 0)
                            .put(SNOW_LAYER, 1)
                            .put(SNOW, 0)
                            .put(DIRT, 1)
                            .put(ICE, 1)
                            .build()
                    ).put(MODIFIED_JUNGLE, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(VINE, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(COCOA, 0)
                            .put(MELON_BLOCK, 0)
                            .build()
                    ).put(MODIFIED_JUNGLE_EDGE,  ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(VINE, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(COCOA, 0)
                            .put(MELON_BLOCK, 0)
                            .build()
                    ).put(TALL_BIRCH_FOREST, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(DOUBLE_PLANT, 0)
                            .build()
                    ).put(TALL_BIRCH_HILLS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(DOUBLE_PLANT, 0)
                            .build()
                    ).put(DARK_FOREST_HILLS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .put(RED_MUSHROOM_BLOCK, 0)
                            .put(BROWN_MUSHROOM_BLOCK, 0)
                            .put(DOUBLE_PLANT, 0)
                            .build()
                    ).put(SNOWY_TAIGA_MOUNTAINS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(SNOW, 0)
                            .put(GRASS, 0)
                            .put(TALLGRASS, 0)
                            .put(DOUBLE_PLANT, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .build()
                    ).put(GIANT_SPRUCE_TAIGA, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(MOSSY_COBBLESTONE, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(TALLGRASS, 0)
                            .put(DOUBLE_PLANT, 0)
                            .put(DEADBUSH, 0)
                            .put(RED_MUSHROOM, 0)
                            .put(BROWN_MUSHROOM, 0)
                            .build()
                    ).put(GIANT_SPRUCE_TAIGA_HILLS, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(MOSSY_COBBLESTONE, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(TALLGRASS, 0)
                            .put(DOUBLE_PLANT, 0)
                            .put(DEADBUSH, 0)
                            .put(RED_MUSHROOM, 0)
                            .put(BROWN_MUSHROOM, 0)
                            .build()
                    ).put(MODIFIED_GRAVELLY_MOUNTAINS, ImmutableMap.<Block, Integer>builder()
                            .put(GRAVEL, 1)
                            .put(DIRT, 1)
                            .put(SNOW, 0)
                            .put(STONE, 1)
                            .put(MONSTER_EGG, 1)
                            .put(EMERALD_ORE, 1)
                            .put(COAL_ORE, 1)
                            .put(IRON_ORE, 1)
                            .build()
                    ).put(SHATTERED_SAVANNA, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(STONE, 1)
                            .put(TALLGRASS, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)

                            .put(GRASS, 0)
                            .build()
                    ).put(SHATTERED_SAVANNA_PLATEAU, ImmutableMap.<Block, Integer>builder()
                            .put(DIRT, 1)
                            .put(STONE, 1)
                            .put(TALLGRASS, 0)
                            .put(LOG2, 0)
                            .put(LEAVES2, 0)
                            .put(LOG, 0)
                            .put(LEAVES, 0)
                            .build()
                    ).put(ERODED_BADLANDS, ImmutableMap.<Block, Integer>builder()
                            .put(SAND, 1)
                            .put(HARDENED_CLAY, 1)
                            .put(STAINED_HARDENED_CLAY, 1)
                            .put(CACTUS, 0)
                            .put(DEADBUSH, 0)
                            .put(GOLD_ORE, 1)
                            .build()
                    ).put(MODIFIED_WOODED_BADLANDS_PLATEAU, ImmutableMap.<Block, Integer>builder()
                            .put(SAND, 1)
                            .put(HARDENED_CLAY, 1)
                            .put(STAINED_HARDENED_CLAY, 1)
                            .put(CACTUS, 0)
                            .put(DEADBUSH, 0)
                            .put(GOLD_ORE, 1)
                            .put(DIRT, 1)
                            .put(LOG, 1)
                            .put(LEAVES, 1)
                            .build()
                    ).put(MODIFIED_BADLANDS_PLATEAU, ImmutableMap.<Block, Integer>builder()
                            .put(SAND, 1)
                            .put(HARDENED_CLAY, 1)
                            .put(STAINED_HARDENED_CLAY, 1)
                            .put(CACTUS, 0)
                            .put(DEADBUSH, 0)
                            .put(GOLD_ORE, 1)
                            .build()
                    )
                    .build()
            )
            .build();

    private static final Map<Block, Integer> overworld = ImmutableMap.<Block, Integer>builder()
            .put(AIR, 0)
            //.put(BEDROCK, 7)
            .put(BEDROCK, 1)
            .put(STONE, 1)
            .put(DIRT, 1)
            .put(WATER, 1)
            .put(LAVA, 1)
            .put(COAL_ORE, 1)
            .put(IRON_ORE, 1)
            .put(GOLD_ORE, 1)
            .put(DIAMOND_ORE, 1)
            .put(EMERALD_ORE, 1)
            .put(LAPIS_ORE, 1)
            .put(REDSTONE_ORE, 1)
            .put(GRAVEL, 1)
            .build();

    private static final Map<Block, Integer> nether = ImmutableMap.<Block, Integer>builder()
            .put(AIR, 0)
            //.put(BEDROCK, 7)
            .put(BEDROCK, 87)
            .put(NETHERRACK, 87)
            .put(LAVA, 11)
            .put(QUARTZ_ORE, 87)
            .build();

    private static final Map<Block, Integer> end = ImmutableMap.<Block, Integer>builder()
            .put(AIR, 0)
            .put(END_STONE, 121)
            .build();

    private Map<Block, Integer> map;
    private final Dimension dimension;

    public SimpleBlockMap(Dimension dimension) {
        this(dimension, PLAINS);
    }

    public SimpleBlockMap(Dimension dimension, Biome biome) {
        this(MCVersion.v1_16_5, dimension, biome);
    }

    public SimpleBlockMap(MCVersion mcVersion, Dimension dimension, Biome biome) {
        this.map = versionedBiomeMap.get(mcVersion).get(biome);
        this.dimension = dimension;
    }

    public void setBiome(Biome biome) {
        this.map = versionedBiomeMap.get(MCVersion.v1_16_5).get(biome);
    }

    public int get(Block block) {
        Integer biomeBlock = this.map.get(block);
        if (biomeBlock == null) {
            if (this.dimension == Dimension.OVERWORLD) {
                return overworld.getOrDefault(block, -1);
            } else if (this.dimension == Dimension.NETHER) {
                return nether.getOrDefault(block, -1);
            } else {
                return end.getOrDefault(block, -1);
            }
        }
        return biomeBlock;
    }
}
